### ISSUE TITLE
comprehensive doc of the structure of dataset

### ISSUE THREAD

**Issue by revesansparole** [Iain530/force-directed-layout-algorithms#1]
I can't understand the structure of dataset. 2D array, what's in the first dimension? what's in the second dimension?

How do I specify a connection between two nodes?

**Comment by Iain530** [comment]
If you consider the first 2 entries in the [iris dataset](https://github.com/Iain530/force-directed-layout-algorithms/blob/master/datasets/iris/iris.csv):
```
[[5.1, 3.5, 1.4 ,0.2, "setosa"]
 [4.9, 3.0, 1.4, 0.2, "setosa"]]
```

Each point in this dataset is a 1D array which has values representing  `Sepal.Length | Sepal.Width | Petal.Length | Petal.Width | Type`.  To include multiple datapoints we make this a 2D array where each entry in the array is the next datapoint.

---

In these algorithms all nodes are connected but the strength/weakness of the connection is determined by the disance function. The distance function is defined like:
```python
def distance(p1: np.ndarray, p2: np.ndarray) -> float:
    # Compare p1 and p2, return the distance they should be placed apart on the graph
    # Low number relative other distances means p1 and p2 will try to be placed close together
    return ...
```

If you are comparing datasets that consist of numbers only you can start with using the simple distance functions defined in [forcelayout/distance.py](https://github.com/Iain530/force-directed-layout-algorithms/blob/master/forcelayout/distance.py#L4) although I highly recommend a custom one afterwards.
